# yaml-language-server: $schema=https://json.schemastore.org/circleciconfig.json
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  node: circleci/node@7.0.0
  pulumi: pulumi/pulumi@2.1.0
  slack: circleci/slack@5.1.1

jobs:
  provision:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - pulumi/login
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v1-provision
          override-ci-command: yarn workspaces focus @hckr-studio/websites-infrastructure
      - pulumi/update:
          working_directory: infrastructure
          stack: prod
          skip-preview: true
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-website

  pre-provision:
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - pulumi/login
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v1-provision
          override-ci-command: yarn workspaces focus @hckr-studio/websites-infrastructure
      - pulumi/preview:
          working_directory: infrastructure
          stack: prod
      - slack/notify:
          event: fail
          template: basic_fail_1
          channel: ntf-website

  build:
    parameters:
      project_name:
        type: string
      site_dir:
        type: string
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v1-build-<< parameters.project_name >>
          override-ci-command: yarn workspaces focus @hckr-studio/<< parameters.project_name >>-web
      - run:
          name: Build << parameters.site_dir >> website
          working_directory: << parameters.site_dir >>
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .blendid/public/<< parameters.site_dir >>
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
          channel: ntf-website

  deploy:
    parameters:
      project_name:
        type: string
      site_dir:
        type: string
    docker:
      - image: cimg/node:lts
    resource_class: arm.large
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install-packages:
          pkg-manager: yarn-berry
          cache-version: v1-build-<< parameters.project_name >>
          override-ci-command: yarn workspaces focus @hckr-studio/<< parameters.project_name >>-web
      - run:
          name: Deploy << parameters.site_dir >> website
          working_directory: << parameters.site_dir >> # change directory to deploy functions
          command: yarn wrangler pages deploy ../.blendid/public/<< parameters.site_dir >> --project-name << parameters.project_name >>
      - slack/notify:
          event: fail
          mentions: '@here'
          template: basic_fail_1
          channel: ntf-website
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
          channel: ntf-website
workflows:
  ci:
    jobs:
      - provision:
          context:
            - pulumi
            - slack
          filters:
            branches:
              only: trunk
      - pre-provision:
          context:
            - pulumi
            - slack
          filters:
            branches:
              ignore: trunk
      - build:
          name: build-hckr-party
          project_name: hckr-party
          site_dir: hckr.party
          context:
            - slack
      - build:
          name: build-hckr-space
          project_name: hckr-space
          site_dir: hckr.space
          context:
            - slack
      - build:
          name: build-hckr-studio
          project_name: hckr-studio
          site_dir: hckr.studio
          context:
            - slack
      - build:
          name: build-hckr-tv
          project_name: hckr-tv
          site_dir: hckr.tv
          context:
            - slack
      - deploy:
          name: deploy-hckr-party
          project_name: hckr-party
          site_dir: hckr.party
          context:
            - cloudflare
            - slack
          requires:
            - build-hckr-party
            - provision
          filters:
            branches:
              only: trunk
      - deploy:
          name: deploy-hckr-space
          project_name: hckr-space
          site_dir: hckr.space
          context:
            - cloudflare
            - slack
          requires:
            - build-hckr-space
            - provision
          filters:
            branches:
              only: trunk
      - deploy:
          name: deploy-hckr-studio
          project_name: hckr-studio
          site_dir: hckr.studio
          context:
            - cloudflare
            - slack
          requires:
            - build-hckr-studio
            - provision
          filters:
            branches:
              only: trunk
      - deploy:
          name: deploy-hckr-tv
          project_name: hckr-tv
          site_dir: hckr.tv
          context:
            - cloudflare
            - slack
          requires:
            - build-hckr-tv
            - provision
          filters:
            branches:
              only: trunk
